config/routes.rb
Subscripty::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :confirmations => 'confirmations'}
  resources :users
  resources :courses do
    resources :purchases
  end
  resources :enrollments
  resources :relationships, :only => [:create, :destroy]
  resources :authentications
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/dashboard', :to => 'users#dashboard'
  match '/courses/:id/purchases/:id/ipn', :to => 'purchases#ipn_notification', :via => :post
  match '/auth/:provider/callback' => 'authentications#create'
  root :to => 'pages#home'
  
  resources :users do
      member do
        get :following, :followers
      end
    end
    
  resources :courses do
    member do
      get :purchase
      post :enroll
      post :ipn
    end
  end
    

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :token_authenticatable, :encryptable, :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :firstname, :lastname, :bio, :zipcode, :state, :city, :earnings, :hours_taught, :hours_learned, :image, :confirmed_at, :sign_in_count
  
  has_many :courses
  has_many :enrollments, :dependent => :destroy
  has_many :courses, :through => :enrollments, :source => "course_id", :dependent => :destroy
  has_many :relationships, :foreign_key => "follower_id", :dependent => :destroy
  has_many :following, :through => :relationships, :source => :followed
  
  has_many :reverse_relationships, :foreign_key => "followed_id",
                                     :class_name => "Relationship",
                                     :dependent => :destroy
  has_many :followers, :through => :reverse_relationships, :source => :follower
  has_many :purchases
  has_many :authentications
  
  validates :firstname,  :presence => true, :length   => { :maximum => 50 }
  validates :lastname,   :presence => true, :length   => { :maximum => 50 }
  
  email_regex = /\A[\w+\-.]+@vanderbilt\.edu\z/i
  
  validates :email, :presence => true,
                    :format => {:with => email_regex, :message => "You must use a vanderbilt.edu email address"}, 
                    :uniqueness => true
  
  mount_uploader :image, AvatarUploader
  
  
  def enroll!(course, user)
    enrollments.create!(:course_id => course.id, :active => true)
    user.hours_learned = user.hours_learned + ((course.endtime - course.starttime)/3600).to_i
    course.user.earnings += course.cost
    user.save
    course.user.save
  end
  
  def enrolled?(course)
    enrollments.find_by_course_id(course)
  end
  
  def unenroll!(course)
    enrollments.find_by_course_id(course).destroy
    self.hours_learned = self.hours_learned - ((course.endtime - course.starttime)/3600).to_i
    course.user.earnings = course.user.earnings - course.cost
    self.save
    course.user.save
  end
  
  def teach!(course, user)
    user.hours_taught = user.hours_taught + ((course.endtime - course.starttime)/3600).to_i
    user.save
  end
  
  def unteach!(course, user)
    user.hours_taught = user.hours_taught - ((course.endtime - course.starttime)/3600).to_i
    user.save
  end
  
  def following?(followed)
    relationships.find_by_followed_id(followed)
  end
  
  def follow!(followed)
    relationships.create!(:followed_id => followed.id)
  end
  
  def unfollow!(followed)
    relationships.find_by_followed_id(followed).destroy
  end
  
  def feed
    Course.from_users_followed_by(self)
  end
  
  def apply_omniauth(omniauth)
    case omniauth['provider']
    when 'facebook'
      self.apply_facebook(omniauth)
    when 'twitter'
      self.apply_twitter(omniauth)
    end
    authentications.build(hash_from_omniauth(omniauth))
  end

  def facebook
    @fb_user ||= FbGraph::User.me(self.authentications.find_by_provider('facebook').token)
  end

  def twitter
    unless @twitter_user
      provider = self.authentications.find_by_provider('twitter')
      @twitter_user = Twitter::Client.new(:oauth_token => provider.token, :oauth_token_secret => provider.secret) rescue nil
    end
    @twitter_user
  end


  protected

  def apply_facebook(omniauth)
    if (extra = omniauth['extra']['user_hash'] rescue false)
      self.email = (extra['email'] rescue '')
    end
  end

  def apply_twitter(omniauth)
    if (extra = omniauth['extra']['user_hash'] rescue false)
      # Example fetching extra data. Needs migration to User model:
      # self.firstname = (extra['name'] rescue '')
    end
  end

  def hash_from_omniauth(omniauth)
    {
      :provider => omniauth['provider'], 
      :uid => omniauth['uid'], 
      :token => (omniauth['credentials']['token'] rescue nil),
      :secret => (omniauth['credentials']['secret'] rescue nil)
    }
  end
  
  
  
  
  
  #def password_required?
    #((authentications.empty? || !password.blank?) && super)
  #end
  
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  before_filter :find_user, :except => [:dashboard]
  
  def show
    @title = @user.id
    @enrollments = @user.enrollments
    @courses = Course.find(:all, :conditions => [ "user_id IN (?)", @user.id], :limit => 50)
  end
  
  def find_user
    @user = User.find(params[:id])
    rescue ActiveRecord::RecordNotFound
      flash[:alert] = "The user you were looking" +
      " for could not be found."
      redirect_to root_path
  end
  
  def following
      @title = "Following"
      @user = User.find(params[:id])
      @users = @user.following
      render 'show_follow'
  end
  
  def followers
      @title = "Followers"
      @user = User.find(params[:id])
      @users = @user.followers
      render 'show_follow'
  end
  
  def dashboard
    @title = "Dashboard"
    if user_signed_in?
    @feed_items = current_user.feed
    end
    @enrollments = current_user.enrollments
    @user = current_user
    @courses = Course.find(:all, :conditions => [ "user_id IN (?)", current_user.id], :limit => 50)
  end
  
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/users/_feed.html.erb
<% if @feed_items.any? %>
  <table class="courses" summary="Status feed">
    <%= render :partial => 'users/feed_item', :collection => @feed_items %>
  </table>
<% end %>

app/views/users/_feed_item.html.erb
<tr>
  <td class="course">
    <span class="user">
      <%= image_tag feed_item.user.image_url(:thumb).to_s %> <%= link_to feed_item.user.firstname, feed_item.user %><%= " posted "%>
    </span>
    <span class="content"><%= link_to feed_item.name, (feed_item) %></span>
    <span class="timestamp">
      <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user == feed_item.user %>
    <td>
      <%= link_to "delete", feed_item, :method => :delete,
                                       :confirm => "You sure?",
                                       :title => feed_item.name %>
    </td>
  <% end %>
</tr>

app/views/users/_follow.html.erb
<%= form_for current_user.relationships.build(:followed_id => @user.id), :remote => true do |f| %>
  <div><%= f.hidden_field :followed_id %></div>
  <div class="actions"><%= f.submit "Follow" %></div>
<% end %>

app/views/users/_follow_form.html.erb
<% unless (current_user == @user) %>
  <div id="follow_form">
  <% if current_user.following?(@user) %>
    <%= render 'unfollow' %>
  <% else %>
    <%= render 'follow' %>
  <% end %>
  </div>
<% end %>

app/views/users/_stats.html.erb
<% @user ||= current_user %>
<div class="stats">
  <table summary="User stats">
    <tr>
      <td>
        <a href="<%= following_user_path(@user) %>">
          <span id="following" class="stat">
            <%= @user.following.count %> following
          </span>
        </a>
      </td>
      <td>
        <a href="<%= followers_user_path(@user) %>">
          <span id="followers" class="stat">
            <%= pluralize(@user.followers.count, "follower") %>
          </span>
        </a>
      </td>
    </tr>
  </table>
</div>

app/views/users/_unfollow.html.erb
<%= form_for current_user.relationships.find_by_followed_id(@user),
             :html => { :method => :delete }, :remote => true do |f| %>
  <div class="actions"><%= f.submit "Unfollow" %></div>
<% end %>

app/views/users/_user.html.erb
<%= user.firstname %>

app/views/users/dashboard.html.erb
<div id = "dashboard_feed">
<% if user_signed_in? %>
  <%= render 'courses/feed' %>
<% else %>
<%= link_to "Sign Up!", new_user_path %>
<% end %>
</div>

app/views/users/show.html.erb
<div id = "profile_top_left">
	<span id = "avatar"><%= image_tag @user.image_url(:profile).to_s %></span>
	<h3><%= @user.firstname + ' ' + @user.lastname %></h3>
	<h4><%= @user.city + ", " + @user.state %></h4>
		<div id = "left-stats">
		<%= render 'stats' %>
		<%= render 'follow_form' if signed_in? %>
		</div>
	<%= link_to "Settings", edit_user_registration_path, :id => "settings", :class => "button1" if signed_in? && @user == current_user %>
	<br></br>
	<p>Hours Taught: <%=@user.hours_taught %></p>
	<p>Hours Learned: <%=@user.hours_learned %></p>
</div>

<div id = "profile_right">
	<p>Taking:</p>
	<% @enrollments.each do |enrollment| %>
		<div class = "course_preview">
			<div class = "course_thumb"><%= image_tag enrollment.course.image_url(:thumb).to_s %>
				<p>Taught by <%= link_to enrollment.course.user.firstname, enrollment.course.user %></p></div>
			<div class = "course_name"><%= link_to enrollment.course.name, enrollment.course %>
				<p>Located in <%= enrollment.course.city + ', ' + enrollment.course.state %></p>
				<p>On <%= enrollment.course.startdate.strftime("%d/%m") %></p>
				</div>
		</div>
	<% end %>
</div>

<div id ="profile_bottom_right">
	<br><p>Teaching:</p></br>
	<% @courses.each do |course| %>
		<div class = "course_preview">
			<div class = "course_thumb"><%= image_tag course.image_url(:thumb).to_s %>
				<p>Taught by <%= link_to course.user.firstname, course.user %></p></div>
			<div class = "course_name"><%= link_to course.name, course %>
				<p>Located in <%= course.city + ', ' + course.state %></p>
				<p>On <%= course.startdate.strftime("%d/%m") %></p>
				</div>
		</div>
	<% end %>
</div>

app/views/users/show_follow.html.erb
<table summary="Information about following/followers">
  <tr>
    <td class="main">
      <h1><%= @title %></h1>
      
      <% unless @users.empty? %>
        <ul class="users">
          <%= render @users %>
        </ul>
      <% end %>
    </td>
    <td class="sidebar round">
      <strong>Name</strong> <%= @user.firstname %><br />
      <strong>URL</strong> <%= link_to user_path(@user), @user %><br />
      <%= render 'stats' %>
    </td>
  </tr>
</table>