config/routes.rb
Subscripty::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :confirmations => 'confirmations'}
  resources :users
  resources :courses do
    resources :purchases
  end
  resources :enrollments
  resources :relationships, :only => [:create, :destroy]
  resources :authentications
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/dashboard', :to => 'users#dashboard'
  match '/courses/:id/purchases/:id/ipn', :to => 'purchases#ipn_notification', :via => :post
  match '/auth/:provider/callback' => 'authentications#create'
  root :to => 'pages#home'
  
  resources :users do
      member do
        get :following, :followers
      end
    end
    
  resources :courses do
    member do
      get :purchase
      post :enroll
      post :ipn
    end
  end
    

end

app/controllers/courses_controller.rb
class CoursesController < ApplicationController
  include ApplicationHelper

  def index
    state = params[:state]
    if (params[:state])
      @courses = Course.where(:state => state)
    elsif current_user
      @courses = Course.where(:state => current_user.state)
    else
      @courses = Course.all
    end
  end
  
  def show
    @course = Course.find(params[:id])
    @user = @course.user
  end
  
  def new
    if user_signed_in?
      @course = Course.new
    else
      redirect_to new_user_registration_path
    end
  end
  
  def create
    @course = Course.new(params[:course])
    @course.user_id = current_user.id
    current_user.teach!(@course, current_user)
    if @course.save
      flash[:notice] = "Course has been created."
      #current_user.twitter.update("Check out my new course on Skillstruct.")
      current_user.facebook.feed!(
        :message => 'I just created a new course on skillstruct', 
        :name => 'My Rails 3 App with Omniauth, Devise and FB_graph'
      )
      redirect_to @course
    else
      flash[:alert] = "Course has not been created."
      render :action => "new"
    end
  end
  
  def edit
    @course = Course.find(params[:id])
  end
  
  def update
    @course = Course.find(params[:id])
    if @course.update_attributes(params[:course])
      flash[:notice] = "Course has been updated."
      redirect_to @course
    else
      flash[:alert] = "Course has not been updated."
      render :action => "edit"
    end
  end
  
  def destroy
    @course = Course.find(params[:id])
    current_user.unteach!(@course, current_user)
    @course.destroy
    flash[:notice] = "Course has been deleted."
    redirect_to courses_path
  end
  
  def purchase
    @course = Course.find(params[:id])
    @user = current_user
  end 
 
  def enroll
    @course = Course.find(params[:id])
    @user = current_user
    course_email = @course.paypal_email
    
    cost = @course.cost
    me = (cost)
    them = (cost*0.75)
    
    pay_request = PaypalAdaptive::Request.new
        data = {
          "returnUrl" => "http://empty-robot-8386.herokuapp.com/courses",
          "requestEnvelope" => {"errorLanguage" => "en_US"},
          "currencyCode" => "USD",
          "receiverList" =>
                  { "receiver" => [
                    {"email" => "zksher_1325804404_biz@gmail.com", "amount"=>me, "primary" => true}, 
                    {"email"=>course_email, "amount"=>them, "primary" => false}
                  ]},
          "cancelUrl" => "http://empty-robot-8386.herokuapp.com/",
          "actionType" => "PAY",
          "ipnNotificationUrl" => "http://empty-robot-8386.herokuapp.com/ipn-notification"
        }

        #To do chained payments, just add a primary boolean flag:{“receiver”=> [{"email"=>"PRIMARY", "amount"=>"100.00", "primary" => true}, {"email"=>"OTHER", "amount"=>"75.00", "primary" => false}]}

        pay_response = pay_request.pay(data)

        if pay_response.success?
            # Send user to paypal
            redirect_to pay_response.approve_paypal_payment_url
        else
            puts pay_response.errors.first['message']
            redirect_to "/", notice: "Something went wrong. Please contact support."
        end
  end
  
  def ipn
    ipn = PaypalAdaptive::IpnNotification.new
        ipn.send_back(request.raw_post)

        if ipn.verified?
          logger.info "IT WORKED"
        else
          logger.info "IT DIDNT WORK"
        end

        render nothing: true
  end
  
end

app/helpers/courses_helper.rb
module CoursesHelper
end

app/views/courses/_enroll.html.erb
<%= form_for current_user.enrollments.build(:course_id => @course.id) do |f| %>
  <div><%= f.hidden_field :course_id %></div>
  <div class="actions"><%= f.submit "Enroll" %></div>
<% end %>

app/views/courses/_enroll_form.html.erb
<% unless current_user == (@course.user) %>
  <div id="follow_form">
  <% if current_user.enrolled?(@course) %>
    <%= render 'unenroll' %>
  <% else %>
    <%= render 'enroll' %>
  <% end %>
  </div>
<% end %>

app/views/courses/_feed.html.erb
<% if @feed_items.any? %>
  <table class="courses" summary="Status feed">
    <%= render :partial => 'courses/feed_item', :collection => @feed_items %>
  </table>
<% end %>

app/views/courses/_feed_item.html.erb
<tr>
  <td class="course">
    <span class="user">
      <%= image_tag feed_item.user.image_url(:thumb).to_s %> <%= link_to feed_item.user.firstname, feed_item.user %><%= " posted "%>
    </span>
    <span class="content"><%= link_to feed_item.name, (feed_item) %></span>
    <span class="timestamp">
      <%= time_ago_in_words(feed_item.created_at) %> ago.
    </span>
  </td>
  <% if current_user == feed_item.user %>
    <td>
      <%= link_to "delete", feed_item, :method => :delete,
                                       :confirm => "You sure?",
                                       :title => feed_item.name %>
    </td>
  <% end %>
</tr>

app/views/courses/_form.html.erb
<div id = "form">
<%= simple_form_for @course, :html => {:multipart => true} do |f| %>
	<%= f.input :name %>
	<%= f.input :description%>
	<%= f.input :category, :collection => (categories_list)%>
	<%= f.input :credentials %>
	<%= f.input :cost %>
	<%= f.input :place %>
	<%= f.label :startdate %>
	<%= f.text_field :startdate %>
	<%= f.input :starttime, :ampm => true %>
	<%= f.label :enddate %>
	<%= f.text_field :enddate %>
	<%= f.input :endtime, :ampm => true %>
	<%= f.file_field :image, :label => 'Your course image' %>
	<%= f.input :attendance %>
	<%= f.input :state, :collection => (us_states)%>
	<%= f.input :zipcode %>
	<%= f.input :city %>
	<%= f.label :Your_Paypal_Email%>
	<%= f.email_field :paypal_email, :label => 'Your Paypal Email' %>
	<%= f.button :submit %>
	
<% end %>
</div>	
	
	

app/views/courses/_unenroll.html.erb
<%= form_for current_user.enrollments.find_by_course_id(@course), :html => { :method => :delete } do |f| %>
  <div class="actions"><%= f.submit "Unenroll" %></div>
<% end %>

app/views/courses/edit.html.erb
<h2>Edit course</h2>
<%= render "form" %>

app/views/courses/index.html.erb
<div id = "index_left">
	
</div>

<div id = "index_right">
	<div id = "course_filter">
		<%= form_tag(courses_path, :method => :get) do |f| %>
			<% if user_signed_in? %>
			<span id = "state_filter>"><%= select_tag(:state, options_for_select(us_states, :selected => params[:state] || current_user.state)) %></span>
			<% else %>
			<span id = "state_filter>"><%= select_tag(:state, options_for_select(us_states)) %></span>
			<% end %>
			<%= submit_tag 'Filter by State' %>
		<% end %>
	</div>
	<% @courses.each do |course| %>
	<div class = "course_preview">
		<div class = "course_thumb"><%= image_tag course.image_url(:thumb).to_s %>
			<p>Taught by <%= link_to course.user.firstname, course.user %></p></div>
		<div class = "course_name"><%= link_to course.name, course %>
			<p>Located in <%= course.city + ', ' + course.state %></p>
			<p>On <%= course.startdate.strftime("%d/%m") %></p>
			</div>
	</div> 
	<% end %>
</div>

app/views/courses/new.html.erb
<h2>New Course</h2> 
<%= render "form" %>

app/views/courses/purchase.html.erb
<p>Purchase Information</p>

<p>Course Total: <%= number_to_currency(@course.cost) %><p>
	
	<%= form_tag(enroll_course_path(@course), :method => "post") do %>
	  <%= label_tag(:paypal_email, "Paypal Email Address")%>
	  <%= text_field_tag(:paypal_email) %>
	  <%= submit_tag("Pay Now") %>
	<% end %>
	
	
	Purchase Model
	t.id int
	t.course_id int
	t.user_id int
	t.teacher_id int
	t.amount int
	t.completed boolean
	t.timestamps 
	
	link_to new_purchase_path(@course)
	
	form_for(@purchase)
	hidden_field: course_id
	hidden_field: current_user.id
	hidden_field: cost
	submit_button: Pay Now
	
	@purchase = params[:purchase]
	
	paypal_method call
	
	if ipn?
		@purchase.save
		current_user.enroll!
		flash "congratulations"
		
	else
		flash "sorry"
		redirect_to @purchase.class
		
	resources :purchases

app/views/courses/show.html.erb
<div id = "course_left">
	<div id = "course_left_image">
		<%= image_tag @course.image_url(:show).to_s %>
	</div>
	<div id = "course_left_title">
		<h1><%= @course.name %></h2>
		<h3>Category: <%= @course.category %></h3>
		<h4>Category Image Here</h4>
	</div>
	<div id = "course_description">
		<span id = "about_course">
			<br></br>
			<h1>About the Course</h1>
		</span>
		<%= @course.description %>
		<span id = "about_course">
			<br></br>
			<h1>Teacher Credentials</h1>
		</span>
		<%= @course.credentials %>
	</div>
</div>

<div id = "course_top_right">
	<div id="course_info">
		<ul>
			<li>Cost<span>$<%=@course.cost%></span></li>
			<li class="bottle">Class Size <span><%=@course.attendance%></span></li>
			<li>Signed Up <em></em><span><%=@course.enrollments.count%></span></li>
		</ul>
	</div>
	<div id = "course_date">
		<p><%= @course.startdate.strftime("%A, %B %d") %></p>
		<p><%= @course.starttime.strftime("%I:%M%p")%> - <%= @course.endtime.strftime("%I:%M%p")%><p>
		<br><p><%= @course.place %></p></br>
	</div>
	<div id = "enroll_form">
	<% if current_user && @course.user == current_user%>
	<% elsif current_user.enrolled?(@course) %>
	<%= "Your are enrolled in this course."%>
	<% else %>
	<%= link_to "Enroll", new_course_purchase_path(@course) %><%#render 'enroll_form' if signed_in? %>
	<% end %>
	</div>
</div>

<div id = "course_bottom_right">
	<div id = "course_bottom_right_image"><%= image_tag @course.user.image_url(:profile).to_s %>
	<br></br>
	<%= link_to @course.user.firstname + '\'s', @course.user%> Course
	</div>
	<% if @course.user == current_user %>
	<div id = "course_options">
	<br><%= link_to "Edit Course", edit_course_path(@course) %></br>
	<%= link_to "Delete Course", @course, :method => :delete, :confirm => "Are you sure you want to delete this course?" %>
	</div>
	<% end %>
	<%= link_to "tweet me", "http://twitter.com/home?status=#{@course.name} #{course_url(@course)}" %>
</div>