config/routes.rb
Subscripty::Application.routes.draw do
  devise_for :users, :controllers => {:registrations => 'registrations', :confirmations => 'confirmations'}
  resources :users
  resources :courses do
    resources :purchases
  end
  resources :enrollments
  resources :relationships, :only => [:create, :destroy]
  resources :authentications
  
  match '/contact', :to => 'pages#contact'
  match '/about',   :to => 'pages#about'
  match '/help',    :to => 'pages#help'
  match '/dashboard', :to => 'users#dashboard'
  match '/courses/:id/purchases/:id/ipn', :to => 'purchases#ipn_notification', :via => :post
  match '/auth/:provider/callback' => 'authentications#create'
  root :to => 'pages#home'
  
  resources :users do
      member do
        get :following, :followers
      end
    end
    
  resources :courses do
    member do
      get :purchase
      post :enroll
      post :ipn
    end
  end
    

end

app/views/layouts/_footer.html.erb
<footer>
  <nav>
    <ul>
      <li><%= link_to "About", about_path %></li>
      <li><%= link_to "Contact", contact_path %></li>
      <li><a href="http://news.railstutorial.org/">News</a></li>
      <li><a href="http://www.railstutorial.org/">Rails Tutorial</a></li>
    </ul>
  </nav>
</footer>

app/views/layouts/_header.html.erb
<header>
	<%= image_tag("teachmelogo.png") %>	
  <nav>
    <ul>
      <li><%= link_to "Home", root_path %></li>
      <% if user_signed_in? %>
	  <li><%= link_to "Dashboard", '/dashboard' %></li>
	  <li><%= link_to "Profile", current_user %></li>
	  <li><%= link_to "Settings", edit_user_registration_path %></li>
	  <li><%= link_to "Sign out", destroy_user_session_path, :method => :delete %></li>
	  <% else %>
	  <li><%= link_to "Sign up", new_user_registration_path %></li>
	  <li><%= link_to "Sign in", new_user_session_path %></li>
      <% end %>
	  <li><%= link_to "Learn", courses_path %></li>
	  <li><%= link_to "Teach", new_course_path %><li>
      <li><%= link_to "Help", root_path %></li>
	  <% if user_signed_in? %>
	  <li>Signed in as <%= current_user.email %></li>
	  <% end %>
    </ul>
  </nav>
</header>

app/views/layouts/_stylesheets.html.erb
<!--[if lt IE 9]>
<script src="http://html5shiv.googlecode.com/svn/trunk/html5.js"></script>
<![endif]-->
<%= stylesheet_link_tag 'blueprint/screen', :media => 'screen' %>
<%= stylesheet_link_tag 'blueprint/print',  :media => 'print' %>
<!--[if lt IE 8]><%= stylesheet_link_tag 'blueprint/ie' %><![endif]-->
<%= stylesheet_link_tag 'custom', :media => 'screen' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
 	<%= csrf_meta_tag %>
	<%= render 'layouts/stylesheets' %>
	<%= stylesheet_link_tag "http://ajax.googleapis.com/ajax/libs/jqueryui/1.7.2/themes/redmond/jquery-ui.css"%>
	<%= javascript_include_tag :application,  
	"http://ajax.googleapis.com/ajax/libs/jquery/1.4.2/jquery.min.js", "http://ajax.googleapis.com/ajax/libs/jqueryui/1.8.1/jquery-ui.min.js"%>
	  </head>
	  <body>
		<div id = "header_wrapper">
			<%= render 'layouts/header' %>
		</div>
	    <div class="container">
	      <section class="round">
			<% flash.each do |key, value| %>
			 <div class="flash <%= key %>"><%= value %></div>
			<% end %>
	        <%= yield %>
	      </section>
		<%# debug(params) if Rails.env.development? %>
	</div>
	<div id = "footer_wrapper">
	<%= render 'layouts/footer' %>
	</div>
</body>
</html>